__title__ = 'flow-network'
__description__ = 'Flow Network C++ Implementation'
__url__ = 'https://github.com/LucienShui/flow-network'
__version__ = '0.1.2'
__build__ = 0x000102
__author__ = 'Lucien Shui'
__author_email__ = 'lucien@lucien.ink'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2020 Lucien Shui'
