# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  macos-build:

    strategy:
      matrix:
        os: [macos-latest]

    name: Build with ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Conda
      uses: s-weigand/setup-conda@v1
    - name: Install dependencies
      run: |
        conda install swig -y
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel twine
    - name: Build and publish
      shell: bash
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        swig -c++ -python flow_network/core/core.i
        python setup.py sdist bdist_wheel
        twine upload dist/*

  windows-build:

    strategy:
      matrix:
        os: [windows-latest]

    name: Build with ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Conda
      uses: s-weigand/setup-conda@v1
    - name: Install dependencies
      run: |
        conda install swig -y
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel twine
    - name: Build and publish
      shell: bash
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        swig -c++ -python flow_network/core/core.i
        python setup.py sdist bdist_wheel
        find dist -name "*.tar.gz" | xargs rm -rf
        twine upload dist/*


  linux-build:
    name: Build with ubuntu-latest
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Conda
        uses: s-weigand/setup-conda@v1
      - name: SWIG generation
        run: |
          conda install swig -y
          swig -c++ -python flow_network/core/core.i
      - name: build and upload manylinux wheels
        uses: Niraj-Kamdar/manylinux-wheel-builder@master
